### ISSUE TITLE
Back button on android should close zoomable box

### ISSUE THREAD

**Issue by lifenautjoe** [OpenbookOrg/openbook-app#124]
The back button on android should close the zoomable photo box.

**Comment by jwsp1** [comment]
...also a click on the screen next to the photo (click on background), IMO

**Comment by WouterJanson** [comment]
Could it be that this issue has already been solved/fixed?

**Comment by lifenautjoe** [comment]
I'll test now with an android phone. Never saw it in the flesh, just took it as given due to multiple reports.

**Comment by jwsp1** [comment]
1) view a profile photo
2) press back button on android (v.0.0.22)
3) in the background, the profile page closes, but not the profile photo

**Comment by lifenautjoe** [comment]
Can confirm. For some reason this does work on the timeline page.

**Comment by lifenautjoe** [comment]
Oh wait! I know why... On the back button interceptor in the home.dart page, we check if the current route has things to pop, if so, pop them and prevent closing the app, if not, close the app.

Well.. when you open a modal that happens on the "master" route, not the timeline, profile, search ,etc. 

Meaning we also need to check if the "root" route can pop and if so,  pop the route before closing the app.

**Comment by lifenautjoe** [comment]
![image](https://user-images.githubusercontent.com/12737509/55194900-2f84ca80-51ab-11e9-9f0c-351f601007c5.png)

**Comment by lifenautjoe** [comment]
That should be `Navigator.of(context, rootRoute:true).canPop()` on the `home.dart` back button interceptor followed by `Navigator.of(context, rootRoute:true).pop()` (Store ref to Navigator.of(context, rootRoute:true) in a var of course)
