### ISSUE TITLE
Post comments overflow screen when too long

### ISSUE THREAD

**Issue by lifenautjoe** [OpenbookOrg/openbook-app#126]
We probably need to change this whole comment thing to be fullscreen like the create post window.

**Comment by Komposten** [comment]
I'd prefer it if it wasn't fullscreen, if possible. It's very useful to be able to scroll through and read comments one is replying to, while composing the reply.

**Comment by tehthom** [comment]
I agree with Komposten. Also wish there want a comment character limit (or that it was much higher.) Some philosophical or political discussion require longer replies.
