### ISSUE TITLE
Downsize posts with a tall photo

### ISSUE THREAD

**Issue by jwsp1** [OpenbookOrg/openbook-app#127]
Posts that contain tall photos (e.g. screenshots) are also very long, and the image can't usually be viewed in its entirety without clicking on it.

You could optionally post images in a square format (with a border on the sides, similar to Instagram) and make them enlarge with a click.

**Comment by lifenautjoe** [comment]
Thanks for reporting @jwsp1 !

**Comment by lifenautjoe** [comment]
Limiting the image to a certain max height and showing an expand image button might be the way to go.
 
![image](https://user-images.githubusercontent.com/12737509/55113216-cd5e9380-50de-11e9-8cb6-6e273fa58a6c.png)

Not ugly as shown in this image, just a simple block using the same theme-dependent color that the `OBAlert` uses and highlighted with the theme primary accent color.

**Comment by jwsp1** [comment]
> Limiting the image to a certain max height and showing an expand image button might be the way to go.
> 
> [image]
>
> Not ugly as shown in this image, just a simple block using the same theme-dependent color that the `OBAlert` uses and highlighted with the theme primary accent color.

Nice idea but I'd rather prefer the whole image at a first glance... (Maybe it's just by bad taste though ;) )
Have you considered actual downsizing by putting the image in a square format? Expand to full size by click.
![Unbenannt](https://user-images.githubusercontent.com/24477557/55115878-ddc63c80-50e5-11e9-8b53-ae82f5af9d59.jpg)

**Comment by Komposten** [comment]
Looking into the down-scaling option at the moment.
On top of down-scaling large images (based on the width of the device), I also changed it so it doesn't upscale small images (unless they are smaller than 10% of the screen width).

Attaching a couple of images to show what it looks like for a few situations:
![image](https://user-images.githubusercontent.com/7335682/55268562-17847800-528b-11e9-9ca7-7f232100cfe8.png)

(@lifenautjoe, what's your/your team's opinion on this approach.)

Note: This might look a bit weird for really, really tall images (like some comics which can be 10 times as tall as wide) as they will become extremely thin.

**Comment by lifenautjoe** [comment]
Yep. I think the prettiest looking approach is having a max height for an
image ( perhaps 3:4 of the screen height) and then showing some indication
or button on top of the image to expand it full screen.

Can be a semi transparen dark button like the one to close the photo modal
in the bottom right of the image with an expand icon.

**Comment by Komposten** [comment]
When you say "max height [...] showing some indication [...] to expand", do you mean "show only part of the image, but have an indicator to show there's more" (akin to the "Expand Post" button in your screenshot above, albeit a bit more discrete and Openbook-y)?

If that's the case, it does have the problem that most portrait photos would trigger this, which could be annoying if many such photos appear in ones feed (can't just see them directly without having to tap-view-close).

**Comment by lifenautjoe** [comment]
Yep. That’s the downside but I do think it’s a better choice than having
empty space on the screen. We can even make the max height he pretty high,
as in just contract the posts that are super long like comic strips.

**Comment by jwsp1** [comment]
Tbh, I don't want to scroll through my feed and click a thousand of times to expand all tall photos. I want to see the content with at one glance.
If that's really the plan, I'd be happy to see an option to disable this "improvement". Personal opinion - maybe I have a bad taste 😜

**Comment by lifenautjoe** [comment]
This would only apply to extremely long images, the ones that currently
you’d have to scroll multiple times to reach the end which for what I’ve
seen so far in other platforms are  rare.

With no limit of height someone can craft an image ( like someone already
did on the test community) with the purpose of annoying people by making it
20 scrolls long.

We can make it a setting but with the default enabled. I think it’s better
to see the expand button and then explicitly disable it than to scroll on
an image for a minute and having to ask or look if there’s any way not to,
or is it a bug ( in the case of a crafted long image ).

**Comment by Komposten** [comment]
I'll give it a shot and see how it turns out. 🙂 

I still think that images that are smaller than the screen width should remain small (unless they are too small), and not be up-scaled to fit the width. Both goes for pictures in the timeline and when they are tapped on.

The image in the posts titled "Very tiny" in my screenshot above looks like this when upscaled:
![image](https://user-images.githubusercontent.com/7335682/55274973-0e24fb00-52df-11e9-8c13-9f8991917987.png)

**Comment by lifenautjoe** [comment]
Hi Jakob,

Please keep it scaled when small, once again to prevent having empty space
on the sides plus in order to keep scrolling smooth, we store the width and
height of the images on the db, then given this, we calculate its aspect
ratio relative to the width screen before even trying to load the image.

This means the size is always predictable without even retrieving the image.

**Comment by Komposten** [comment]
Can someone who's more artistically gifted than I do a mock-up of what it should look like? (Need an icon to use, and probably some visual indication that the bottom of the image is cut off.)

Also, should the expand button expand the image in situ or open the zoomable photo modal?

**Comment by lifenautjoe** [comment]
Good point.

It should already open the modal, so then the button is simply a way to
know that the post was contracted.

I’ll come up with some mockups later today :-)

**Comment by Komposten** [comment]
@lifenautjoe I know you've been really busy the last few days with trying to get the timeline optimisations working, so don't worry about this until you have time. Still, just bumping it in case you forgot about it. 😉

**Comment by lifenautjoe** [comment]
Without expand

![wo-expand](https://user-images.githubusercontent.com/12737509/56082698-225b1300-5e1c-11e9-9f3c-9b4a09afdbdd.png)


With expand

![expand](https://user-images.githubusercontent.com/12737509/56082700-2ab34e00-5e1c-11e9-99c7-7a63498d27aa.png)


Basically the image is set as a square (screen.width * screen.width) with `fit: BoxFit.cover` property with a button on the right which indicates it can be expanded.

When tapped, preserves the same current behavior of opening the img in the image preview modal.

**Comment by Komposten** [comment]
That's almost exactly what I have (although I'm using a different aspect ratio limit). I think I basically just need to add the background and change the icon of the button. 👍

**Comment by lifenautjoe** [comment]
Awesome! 👯‍♂️

**Comment by lifenautjoe** [comment]
Question, is the max height configurable? perhaps we can make it a ratio of the height of the screen. If a post is > 3/4 of the screen height, display like this 🤔 .

**Comment by Komposten** [comment]
This is the current code: `imageHeight < screenHeight*.75 ? imageHeight : screenHeight*.75`

**Comment by lifenautjoe** [comment]
Alright, seems reasonable. I'll test it out once you give green light 🚦 .
