### ISSUE TITLE
Add crashlytics to get some visibility into issues 

### ISSUE THREAD

**Issue by lifenautjoe** [OpenbookOrg/openbook-app#152]
We're a bit blind currently with device crashes.

**Comment by jwsp1** [comment]
Have you considered https://matomo.org/ or https://www.etracker.com/ as an alternative? 
Crashlytics belongs to Google and I don't think openbook should start sharing user data with such a company...

**Comment by lifenautjoe** [comment]
Ah damn... didn’t know they got acquired by google 🙃

Will look into those and definitely skip crashlytics.

Thank you!

**Comment by lifenautjoe** [comment]
I've integrated Sentry now. It's great because means we can setup our own sentry server and still have visibility of crashes.
