### ISSUE TITLE
Post Photo button gets cut off on iPhoneXR

### ISSUE THREAD

**Issue by uiboy** [OpenbookOrg/openbook-app#182]
When posting something, you see a "Photo" yellow button on the bottom. That is getting cut off for some users on the iPhone XR. Probably it needs to be in the safe area?

**Comment by lifenautjoe** [comment]
Down there is considered safe area by Flutter, so we probably need to add some extra padding always to the bottom sheet pickers. Otherwise we need to detect when we're running on iPhoneXR which is ugly.
