### ISSUE TITLE
Copy text

### ISSUE THREAD

**Issue by lifenautjoe** [OpenbookOrg/openbook-app#211]
Would be nice to have a way to copy text from posts and comments.

Selecting and copying text might be impossible currently due to Flutter ( https://github.com/flutter/flutter/issues/5422 ) but we can build something that when holding  top, shows a copy text dialog for now.

**Comment by Komposten** [comment]
1) Can't remember which app, but some just copy the text automatically if you long-tap it (i.e. it doesn't show a "copy text" button when long tapping, but just copies immediately). Is a pop-up button or instant copy preferrable?
2) Would it be a good idea to add "Copy text" to the post's "three-dot menu" as well, or is that overkill?

**Comment by lifenautjoe** [comment]
Oh instant copy sounds better! We can show a toast to show that the text was copied :)

**Comment by lifenautjoe** [comment]
Fixed with #214 !
