### ISSUE TITLE
Allow copying text from comments

### ISSUE THREAD

**Issue by uiboy** [OpenbookOrg/openbook-app#215]
Users should be able to copy text to their clipboard from comments including comments left by others. We will show this as part of the menu that will pop up on longPress on any comment.

**Comment by lifenautjoe** [comment]
Duplicate of https://github.com/OpenbookOrg/openbook-app/issues/211 and a PR is currently open on this

**Comment by lifenautjoe** [comment]
Uh wait, there might be a conflict here. As the PR is currently hold to copy text and we're doing the hold to show a bottom sheet.

**Comment by uiboy** [comment]
duplicate of #211
