### ISSUE TITLE
Swipe up to dismiss photo view box

### ISSUE THREAD

**Issue by lifenautjoe** [OpenbookOrg/openbook-app#79]
As in so many apps, swiping an image away has become a standard UX pattern.

Make it so that when opening an image, it can be dismissed by swiping it up/down.

Considerations to take are that the image is zoomable therefore some gesture collisions might occur. We need to consider some sort of offset where such behaviour gets triggered.

**Comment by lifenautjoe** [comment]
@cyriana if you can comment over here, I can assign this to you temporarily 😁

**Comment by cyriana** [comment]
I am looking into it. 😊

**Comment by lifenautjoe** [comment]
Someone mentioned that they needed to swipe either really fast or really far to get this to work, can we tweak these a bit?
