### ISSUE TITLE
Back button on android closes the app

### ISSUE THREAD

**Issue by lifenautjoe** [OpenbookOrg/openbook-app#87]
The back button closes the app in android instead of popping the last state.

**Comment by lifenautjoe** [comment]
https://github.com/flutter/flutter/issues/8163

**Comment by smkhalsa** [comment]
@lifenautjoe I'm still having this issue. Is there a setting I need to change to prevent the app from closing when I tap the Android back button?

**Comment by ManukumarSB** [comment]
@lifenautjoe same issue App closes on android back button press instead of navigating back to the previous screen.

**Comment by vahurh** [comment]
Having the same issue as well with my CupertinoApp.
